pl111_drm-y +=	pl111_drm_device.o \
		pl111_drm_connector.o \
		pl111_drm_crtc.o \
		pl111_drm_cursor.o \
		pl111_drm_dma_buf.o \
		pl111_drm_encoder.o \
		pl111_drm_fb.o \
		pl111_drm_gem.o \
		pl111_drm_pl111.o \
		pl111_drm_platform.o \
		pl111_drm_suspend.o \
		pl111_drm_vma.o	\
		pl111_drm_fbdev.o

obj-$(CONFIG_DRM_PL111) += pl111_drm.o
